42Student-July/minishell

parser/print_cmd.c
repl/start_repl.c

Closes #
- print_cmd が壊れていたので修正した
- print_lists と `print-files` に分割
-
-
-
-
n.m hr

fix: print_cmdの修正

---

lexer/next_token.c

Closes #
- `/home/` とか `~/Dict` などを認識できるように修正した
-
-
-
-
-
n.m hr

fix: ~, /, . を認識するように変更

---

Makefile
command/Makefile

Closes #
- Linuxでのrelinkを修正した
- 依存するファイルが重複していた点を修正した
-
-
-
-
n.m hr

fix: ルールの重複により、Linuxでrelinkしていた点を修正

---

error_handle/error_handle.c
lexer/new_ident_token.c

Closes #
- 表題の通り
-
-
-
-
-
n.m hr

fix: チルダやスラッシュが認識できなかった点を修正

---

command/includes/command.h
command/src/convert_arglst_to_array.c
command/src/no_pipe_process.c
command/src/pipe_process.c
parser/delete_cmd.c
parser/parse_exec.c
parser/parse_pipe.c
parser/parse_redirect.c
parser/parser.h
parser/print_cmd.c
repl/start_repl.c

Closes #
- `t_exec_cmd` と `t_redirect_cmd` を 1つの構造体に統合した
- `exec_cmd` 関連にも影響が有ることに注意
- 
-
-
-
n.m hr

`t_exec_cmd` と `t_redirect_cmd` を 1つの構造体に統合

---

command/includes/command.h
command/src/convert_arglst_to_array.c
command/src/no_pipe_process.c
command/src/pipe_process.c
parser/delete_cmd.c
parser/parse_exec.c
parser/parse_pipe.c
parser/parse_redirect.c
parser/parser.h
parser/print_cmd.c
repl/start_repl.c

Reverts 42Student-July/minishell#16

Revert "`t_exec_cmd` と `t_redirect_cmd` を 1つの構造体に統合"

---

command/includes/command.h
command/src/create_cmd.c
command/src/execute_self.c
command/src/no_pipe_process.c
command/src/pipe_process.c

多段パイプの実装にselfコマンドを入れ込みました。
self | selfのコマンドで実行したときに出力が2重になってしまうバグが残っています

パイプの中にselfコマンドを追加

---

command/src/execute_self.c
command/src/pipe_process.c
self_cmd/self_cmd.h
self_cmd/self_echo.c
self_cmd/self_pwd.c

pwdの多段パイプの挙動を調整

---

lexer/is_forbidden_char.c

fix: =を弾かないように修正

---

parser/parse_pipe.c

refactor: commandがないときはcmd_lstにnullを返す

---

command/Makefile
command/includes/command.h
command/includes/execute_struct.h
command/src/cmd_utils.c
command/src/execute_builtin.c
command/src/execute_self.c
command/src/no_pipe_process.c
command/src/pipe_process.c
command/src/redirect_process.c
error_handle/error_handle.h
repl/start_repl.c

元々あったやつを親プロセスでも実行できるようにちょっと改造しました
参考
https://stackoverflow.com/questions/9084099/re-opening-stdout-and-stdin-file-descriptors-after-closing-them

redirectの実装

---

command/includes/command.h
command/includes/execute_struct.h
command/src/execute.c
command/src/no_pipe_process.c
command/src/pipe_process.c
command/src/redirect_process.c
environ/Makefile
environ/environ.h
environ/export_lst.c
environ/lst_utils_2.c
error_handle/error_handle.h
libft/Makefile
libft/ft_kvsreplace_value.c
libft/libft.h
self_cmd/self_cd.c
self_cmd/self_cmd.h
self_cmd/self_export.c
self_cmd/self_pwd.c

cdしたときに環境変数のpwdとoldpwdを更新するメソッドを追加

---

lexer/Makefile
lexer/add_heredoc_delimiter.c
lexer/is_forbidden_char.c
lexer/lexer.h
lexer/new_ident_token.c
lexer/next_token.c

Closes #
- 禁止していた文字種を開放した
-
-
-
-
-
n.m hr

refactor: 禁止されていた文字種を許可するようにした

---

Makefile
lexer/Makefile
lexer/expand_envvar.c
lexer/lexer.h
libft/ft_lstiter.c
libft/libft.h
repl/start_repl.c
test/expand_envvar_test.cpp

feat: 環境変数を展開する関数の実装

---

lexer/read_heredoc.c
repl/start_repl.c

Closes #36
- 表題の通り
- 多分衝突しないので大丈夫でしょう
-
-
-
-
n.m hr

fix: heredocsのファイル名衝突の修正

---

Makefile
lexer/Makefile
lexer/expand_quote.c
lexer/lexer.h
repl/start_repl.c
test/expand_quote_test.cpp
test/test_helper.cpp
test/test_helper.h

Closes #
- `"`, `'` を展開した
-
-
-
-
-
n.m hr

feat: quoteの展開

---

Makefile
lexer/expand_envvar.c
lexer/lexer.h
repl/start_repl.c
test/expand_envvar_test.cpp

Closes #35 
- 環境変数の `"`, `'` への適用をした
-
-

環境変数の展開を`'` の中で抑制する

---

lexer/expand_envvar.c

echo "$" への対応

---

command/src/pipe_process.c
environ/export_lst.c

if-elseをつけたら動いた
あとexportのバグをちょこっと修正

self | extコマンドがちゃんと実行できるように実装

---

lexer/Makefile
lexer/add_heredoc_delimiter.c
lexer/is_valid_tokens.c
lexer/lexer.h
lexer/next_token.c
parser/Makefile
parser/cmd_init.c
parser/is_valid_cmds.c
parser/parse_cmd.c
parser/parse_exec.c
parser/parse_pipe.c
parser/parser.h
repl/start_repl.c

Closes #73
- すべてbashの挙動に合わせるのは不可能だったため、syntax errorとだけ返すようにした
- メモリリークしていることに注意
-

syntax error の出力

---

command/src/pipe_process.c
error_handle/Makefile
error_handle/error_handle.h
error_handle/print_cmd.c

lstの持ち回りを変えたら行けました
あとparser.hでつかっていたprint_cmdを移動したいのですが、依存関係がparser->error_handleになってしまうのでparser.hで使っているt_cmdを読み込めず、仕方なく複製しました。
全体で使う構造体はどこかのcommon.hに置きたい気持ち

3段パイプが実行できていなかったのでfix

---

self_cmd/self_cmd_utils.c

"_"が環境変数のkeyにあっても許可するように対応

---

environ/env_lst.c

MOD: envに存在する値を更新する機能を実装

---

command/src/no_pipe_process.c
repl/start_repl.c
signal/src/sigaction.c

Closes #
- すべてのwait関数をwaitpid関数に変更
- signalを受け取ったときの終了ステータスの更新の仕方を変更
- 終了ステータスをプロンプトで表示する関数を使いやすいように修正
-
-
-
n.m hr

wait関数とsignal周りを修正

---

repl/start_repl.c

fix: print_exit_status関数をコメントアウト

---

command/Makefile
command/includes/command.h
command/src/free_pipe_attr.c
command/src/pipe_process.c

Closes #
- t_pipe_attrをfreeする関数を実装
-
-
-
-
-
n.m hr

t_pipe_attrをfreeする関数を実装

---

self_cmd/self_exit.c

exitする際にget_arg1を呼んでいる箇所でnull checkを追加

---

self_cmd/self_exit.c

FIX: 引数なしでexitしたときにsegvするバグを修正

---

command/includes/execute_struct.h
command/src/init.c
environ/env_lst.c
libft/ft_kvsreplace_value.c
self_cmd/self_cd.c
self_cmd/self_cmd.h
self_cmd/self_env.c
self_cmd/self_export.c
self_cmd/self_unset.c

pwdをunsetしたときのcdの挙動を追加

---

environ/env_lst.c

Closes #
- store_allenv_in_envlst関数のsplitの返り値をfreeするところで、右辺がない環境変数をfreeするとエラーになる
- 一時的にfreeしている箇所をコメントアウト(解決してない)
-
-
-
-
n.m hr

エラーの原因をコメントアウト

---

command/includes/execute_struct.h
command/src/no_pipe_process.c
command/src/redirect_process.c
self_cmd/self_cd.c

Closes #
- redirect_dev_null関数をコメントアウトを解除し、正常に動作するように修正
-
-
-
-
-
n.m hr

redirect_dev_null関数が機能するように修正

---

command/sandbox/signal_test.c
lexer/Makefile
lexer/lexer.h
lexer/read_heredoc.c
main.c
repl/start_repl.c
signal/Makefile
signal/includes/sigaction.h
signal/src/reset_signal_handler.c
signal/src/set_signal_handler_during_command.c
signal/src/set_signal_handler_during_heredoc.c
signal/src/set_signal_handler_during_readline.c
signal/src/sigaction.c

Closes #
-
-
-
- readlineの挙動が安定しない
- heredoc中にSIGNITを送ると、たまにプロンプトが表示されなかったり、プロンプトが表示されていても入力できなかったりする。
- 子プロセスと親プロセスをgdbでデバッグのが難しい

WIP: heredoc中にsignalを受け取ったとき、即座に終了せずプロンプトを表示させる

---

lexer/Makefile
lexer/filter_null_literal_token.c
lexer/lexer.h
lexer/token_dup.c
lexer/word_split.c
repl/start_repl.c
test/expand_envvar_test.cpp
test/test_helper.cpp

Closes #109
- spaceのみのtokenをNULLにした(""ではない)
- token->literal == NULL のtokenを削除する`filter_null_literal_token` を実装した
-
-
-
-
n.m hr

feat: 変数展開した文字が空白文字のみの場合、項として認識しなくする

---

command/includes/command.h
command/src/execute_self.c
command/src/no_pipe_process.c
command/src/pipe_process.c
self_cmd/self_cmd.h
self_cmd/self_exit.c
test/test_sh/cases/exit.txt

- exitコマンドのリファクタ
- pipeでexitコマンドを実行するときのエラーメッセージと終了ステータスが異なっていたため修正
-

exitコマンドのリファクタとpipeのときの挙動を修正

---

self_cmd/self_echo.c

fix: argsがないとき、改行文字を出力する

---

command/src/redirect_process.c
test/test_sh/cases/redirect.txt

要約
STDINのdup2がSTDOUTになっていたので、削除

FIX: STDINのバグ修正

---

lexer/delete_lexer.c
parser/delete_cmd.c
test/expand_envvar_test.cpp
test/lexer_test.cpp

Closes #
- memory leak を修正した
-
-
-
-
-
n.m hr

lexer関連でうまくdeleteできていなかったインスタンスの memory leak の修正

---

command/src/create_cmd.c
command/src/execute_builtin.c
command/src/no_pipe_process.c
command/src/pipe_process.c
error_handle/error_handle.c

execveの引数3つのfree
opendirのleakを解消

コマンド実行のleakを解消

---

error_handle/error_handle.c
lexer/Makefile
lexer/analyze_lex.c
lexer/delete_lexer.c
lexer/lexer.h
repl/start_repl.c

Closes #
- REPLの実行部に処理をベタ書きしていた部分があったので、1つの関数に纏めた
-
-
-
-
-
n.m hr

refactor: lexerの実行部をreplから分離した

---

error_handle/error_handle.c
lexer/Makefile
lexer/analyze_lex.c
lexer/delete_lexer.c
lexer/delete_lexer_product.c
lexer/lexer.h
lexer/new_lexer.c
repl/start_repl.c
test/word_splitting_test.cpp

Closes #
- `ea->cmd_lst` のfreeの方法が異なっていたため修正した
-
-

fix: cmd のfreeのリークを削除した

---

command/src/pipe_process.c
parser/delete_cmd.c

Closes #
- 表題の通り
- double free になっていたため修正
-
-
-
-
n.m hr

fix: pipe が有るときに args をフリーしていた箇所を修正

---

lexer/read_heredoc.c

fix: 親プロセスでfreeされていなかったheredoc delimiterをfree

---

repl/repl.h
repl/start_repl.c

/replのnorm対応

---

lexer/analyze_lex.c

fix:analyze_lexの関数を分割

---

lexer/new_ident_token.c
lexer/new_token.c
lexer/token_dup.c

fix:new_ident_tokenの関数を分割

---

command/src/create_cmd.c

ft_kvsget_value関数の戻り値にNULLが入っていないか確認する処理を追加

fix: env_pathのNULLガードを追加

---

lexer/Makefile
lexer/create_tmpfile.c
lexer/lexer.h
lexer/read_heredoc.c

fix:read_heredoc.cの分割

---

lexer/filter_null_literal_token.c

fix: 条件式を関数化

---

self_cmd/self_cmd.h
self_cmd/self_export.c
self_cmd/self_unset.c

unset と exportのexit statusを追加

---

lexer/Makefile
lexer/join_line_to_buffer.c
lexer/lexer.h
lexer/read_heredoc.c
lexer/register_heredocs.c

fix: read_heredoc.cの関数を分割

---

environ/export_lst.c
libft/Makefile
libft/ft_separate.c
libft/libft.h
self_cmd/self_cmd.h
self_cmd/self_export.c

exportのleakを解消

---

lexer/word_split.c

fix: word_splitを分割

---

lexer/Makefile
lexer/lexer.h
lexer/word_split.c
lexer/word_split_2.c

fix: ファイルを分割

---

lexer/Makefile
lexer/expand_envvar.c
lexer/expand_envvar_2.c
lexer/lexer.h

fix: ファイル分割

---

environ/environ.h
environ/lst_utils.c
self_cmd/self_unset.c

unset leak

---

parser/parse_cmd.c

fix: 関数を分割

---

test/test_sh/cases/expand.txt
test/test_sh/cases/export.txt

Closes #
- 表題の通り
- #172 用のテストケースを追加した
- #163 に使用する

feat: word splittingのtestcaseを追加

---

command/src/no_pipe_process.c
command/src/pipe_process.c

- cmdvのfreeする行を変更
- cmdvのfree忘れを修正
-

cmdvのfree忘れを修正

---

command/src/init.c

FIX: env -i に対応。pwdも初期化するように修正
